server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: 4444
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none